kind: pipeline
name: klass-subsets-service

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn install
    when:
      event:
        - pull_request
        - push

  - name: publish-docker
    image: plugins/gcr
    settings:
      repo: prod-bip/klass-subsets-service
      registry: eu.gcr.io
      tags: "${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:8}"
      json_key:
        from_secret: gcr_credentials
    when:
      branch:
        - development
      event:
        - push
    depends_on:
      - install

---
kind: secret
name: gcr_credentials
get:
  path: drone-gcr-credentials
  name: gcr-credentials
